/**
 * src/lib/version.test.ts
 *
 * Guards the version pipeline: ensures version.json (generated by
 * scripts/gen-version.mjs) passes the Zod schema and has expected shape.
 * Run: npm test  |  make test
 */

import { describe, it, expect } from "vitest";
import { getVersion } from "./version";

describe("getVersion()", () => {
  it("returns a valid Version object without throwing", () => {
    expect(() => getVersion()).not.toThrow();
  });

  it("all fields are non-empty strings", () => {
    const v = getVersion();
    for (const [key, value] of Object.entries(v)) {
      expect(typeof value, `${key} should be a string`).toBe("string");
      expect(value.length, `${key} should be non-empty`).toBeGreaterThan(0);
    }
  });

  it("number looks like a semver-ish string", () => {
    const { number } = getVersion();
    expect(number).toMatch(/^\d+\.\d+/);
  });

  it("sha is a hex short-hash or 'unknown'", () => {
    const { sha } = getVersion();
    expect(sha).toMatch(/^[0-9a-f]{5,}$|^unknown$/);
  });

  it("date is in YYYY-MM-DD format or a valid fallback", () => {
    const { date } = getVersion();
    expect(date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});
