import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { SiteChrome } from "@/components/site-chrome";
import { WormholeProvider } from "@/components/transition/WormholeTransition";
import { getResume } from "@/lib/resume";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const resume     = getResume();
const titleFull  = `Andrew Lass — ${resume.headline}`;
const ogDesc     = resume.pillars.join(" · ");

// ── Structured data ────────────────────────────────────────────────────────────
const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: resume.name,
  jobTitle: resume.headline,
  url: "https://andrewlass.com",
  sameAs: [
    `https://github.com/${resume.contact.github}`,
    ...(resume.contact.linkedin
      ? [`https://linkedin.com/in/${resume.contact.linkedin}`]
      : []),
  ],
  knowsAbout: [...resume.pillars, ...(resume.clouds ?? []), ...(resume.industries ?? [])],
  worksFor: resume.experience[0]
    ? { "@type": "Organization", name: resume.experience[0].company }
    : undefined,
  alumniOf: resume.education.map((e) => ({
    "@type": "CollegeOrUniversity",
    name: e.school,
  })),
  email: resume.contact.email,
};

export const metadata: Metadata = {
  metadataBase: new URL("https://andrewlass.com"),
  title: {
    default:  titleFull,
    template: "%s | Andrew Lass",
  },
  description:
    `Personal portfolio of Andrew Lass — ${resume.headline} specializing in cloud security, networking, and infrastructure automation.`,
  openGraph: {
    type:        "website",
    locale:      "en_US",
    url:         "https://andrewlass.com",
    siteName:    "Andrew Lass",
    title:       titleFull,
    description: ogDesc,
    // OG image generated by src/app/opengraph-image.tsx (1200×630)
  },
  twitter: {
    card:        "summary_large_image",
    title:       titleFull,
    description: ogDesc,
  },
  robots: { index: true, follow: true },
};

// Cloudflare Web Analytics (cookieless). Set NEXT_PUBLIC_CF_BEACON_TOKEN to the
// site token from the Cloudflare dashboard → Web Analytics. No-op when unset.
const cfBeaconToken = process.env.NEXT_PUBLIC_CF_BEACON_TOKEN;

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
      </head>
      <body className="flex min-h-dvh flex-col bg-[var(--color-bg)] text-[var(--color-text)]">
        {/* WormholeProvider mounts the fixed overlay canvas for route transitions */}
        <WormholeProvider>
          {/* SiteChrome renders Nav + Footer, except on immersive routes (/journey) */}
          <SiteChrome>{children}</SiteChrome>
        </WormholeProvider>
        {cfBeaconToken && (
          <Script
            src="https://static.cloudflareinsights.com/beacon.min.js"
            strategy="afterInteractive"
            data-cf-beacon={JSON.stringify({ token: cfBeaconToken })}
          />
        )}
      </body>
    </html>
  );
}
